name: express-app-template

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express_app_template
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U postgres -d postgres'"
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - net

  server:
    image: ssamsara98/express-app-template:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - .:/app:delegated
      - /app/node_modules
    networks:
      - net
    working_dir: /app
    command: [ "sh", "-c", "npm run start:debug" ]
    stdin_open: true
    tty: true
    env_file:
      - .env

volumes:
  pgdata:


networks:
  net:
