# fly.toml app configuration file generated for express-app-template on 2024-08-12T12:08:24+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'express-app-template'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
